=== mt20180064/reactcodegenerator/src/main/xsd/useCaseModel.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="specification" type="specification"/>
    <xs:complexType name="specification">
        <xs:sequence>
            <xs:element name="useCase" type="useCase" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="useCase" >
        <xs:sequence>
            <xs:element name="actor" type="actor" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="entity" type="entity" />
            <xs:element name="mainScenario" type="mainScenario" minOccurs="1"></xs:element>
            <xs:element name="alternativeScenarios" type="alternativeScenario" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="include" type="include" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="usecaseID" type="xs:ID" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="precondition" type="xs:string"/>
        <xs:attribute name="postcondition" type="xs:string"/>
        <xs:attribute name="order" type="xs:int" use="required"/>
        <xs:attribute name="mode" type="xs:string" use="required"/>
    </xs:complexType>
	
    <xs:complexType name="actor">
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="scenarioStep">
        <xs:sequence>
            <xs:element name="extends" type="extends" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="stepNumber" type="xs:int" use="required"/>
        <xs:attribute name="action" type="action" use="required"/>
        <xs:attribute name="entity" type="xs:IDREF" use="required" />
    </xs:complexType>
    <xs:complexType name="entity">
        <xs:sequence>
            <xs:element name="attribute" type="attribute" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="attribute">
        <xs:complexContent>
            <xs:extension base="entity">
                <xs:attribute name="type" type="attributeType" default="STRING" use="optional"/>
                <xs:attribute name="identity" type="xs:boolean" default="false" use="optional"/>
                <xs:attribute name="required" type="xs:boolean" default="true" use="optional"/>
                <xs:attribute name="validation" type="validationType" default ="structuralContext" use = "optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="mainScenario">
        <xs:sequence>
            <xs:element name="step" type="scenarioStep" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="alternativeScenario">
        <xs:sequence>
            <xs:element name="steps" type="scenarioStep" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="referenceMainScenarioNumber" type="xs:int" use="required"/>
        <xs:attribute name="precondition" type="xs:string"/>
        <xs:attribute name="errorMessage" type="xs:string"/>
    </xs:complexType>
    <xs:simpleType name="action">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ENTRY"/>
            <xs:enumeration value="SELECTION"/>            
            <xs:enumeration value="REQUEST_OPERATION"/>
            <xs:enumeration value="SYSTEM_ACTION"/>
            <xs:enumeration value="OPERATION_REPORT"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="validation">
             <xs:attribute name="validationType" type="validationType" default="structuralContext" use="optional"/>
    </xs:complexType>
    <xs:simpleType name="validationType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="structuralContext"/>
            <xs:enumeration value="generalContext"/>
            <xs:enumeration value="domainContext"/>
        </xs:restriction>
    </xs:simpleType>
    
        
    <xs:simpleType name="attributeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="NUMBER"/>
            <xs:enumeration value="STRING"/>
            <xs:enumeration value="DATE"/>
            <xs:enumeration value="LOGICAL"/>
        </xs:restriction>
    </xs:simpleType>
    
        
    <xs:complexType name="include">
        <xs:attribute name="child" type="xs:IDREF" use="required"/>
        <xs:attribute name="joinedByAttribute" type="xs:IDREF" use="required"/>
    </xs:complexType>
        
    <xs:complexType name="extends">
		
        <xs:attribute name="useCase" type="xs:IDREF"/>
        <xs:attribute name="joinedByAttribute" type="xs:IDREF" use="required"/>
		
    </xs:complexType>
        
</xs:schema>

=== mt20180064/reactcodegenerator/src/main/resources/specification.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xsi:noNamespaceSchemaLocation="D:\Radovi\Doktorat\AlatiZaKreiranjeUlazneSpecifikacije\NovaVerzijaUlazneSpecifikacije\useCaseModel.xsd" 
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >

    <useCase    
        usecaseID="UCPrijavaSudije" 
        name="PrijavaSudije" 
        precondition="Nema preduslova" 
        postcondition="Nema postuslova"
        order="1"
        mode="formMode"
    >
  <actor name="Sudija"/>
  <entity id="EntitySudija" name="Sudija">
    <attribute id="username" name="username" type="STRING" validation="generalContext"/>
    <attribute id="password" name="password" type="STRING" validation="generalContext"/>
  </entity>
  <mainScenario>
    <step stepNumber="1" action="ENTRY" entity="username"/>
    <step stepNumber="2" action="ENTRY" entity="password"/>
    <step stepNumber="3" action="REQUEST_OPERATION" entity="EntitySudija"/>
    <step stepNumber="4" action="SYSTEM_ACTION" entity="EntitySudija"/>
    <step stepNumber="5" action="OPERATION_REPORT" entity="EntitySudija"/>
  </mainScenario>
</useCase>
<useCase 
        usecaseID="UCKreiranjeIgraca" 
        name="KreiranjeIgraca" 
        precondition="Nema preduslova" 
        postcondition="Nema postuslova"
        order="2"
        mode="formMode"
    >
  <actor name="Sudija"/>
  <entity id="EntityIgrac" name="Igrac">
    <attribute id="igracID" name="igracID" type="NUMBER" identity="true" validation ="structuralContext"/>
    <attribute id="name" name="name"  type="STRING" validation="generalContext" />
    <attribute id="surname" name="surname"  type="STRING" validation="generalContext" />
    <attribute id="rejting" name="rejting" type="NUMBER" validation="domainContext"/>
    <attribute id="kategorija" name="kategorija" type="STRING" validation="domainContext"/>
    <attribute id="klub" name="klub" type="NUMBER" validation="structuralContext"/>
  </entity>
  <mainScenario>
    <step stepNumber="1" action="ENTRY" entity="name"/>
    <step stepNumber="2" action="ENTRY" entity="surname"/>
    <step stepNumber="3" action="ENTRY" entity="rejting"/>
    <step stepNumber="4" action="ENTRY" entity="kategorija"/>
    <step stepNumber="5" action="SELECTION" entity="klub"></step>
    <step stepNumber="6" action="REQUEST_OPERATION" entity="EntityIgrac"/>
    <step stepNumber="7" action="SYSTEM_ACTION" entity="EntityIgrac"/>
    <step stepNumber="8" action="OPERATION_REPORT" entity="EntityIgrac"/>
  </mainScenario>
</useCase>
<useCase 
        usecaseID="UCKreiranjeTurnira" 
        name="KreiranjeTurnira" 
        precondition="Nema preduslova" 
        postcondition="Nema postuslova"
        order="3"
        mode="formMode"
    >
  <entity id="EntityTurnir" name="Turnir">
    <attribute id="TurnirID" name="TurnirID" type="NUMBER"  identity="true" validation = "structuralContext"/>
    <attribute id="naziv" name="naziv" type= "STRING" validation="domainContext"/>
    <attribute id="mesto" name="mesto" type= "STRING" validation="domainContext"/>
    <attribute id="tip" name="tip" type= "STRING" validation="domainContext"/>
    <attribute id="tempo" name="tempo" type= "STRING" validation="domainContext"/>
  </entity>
  <mainScenario>
    <step stepNumber="1" action="ENTRY" entity="naziv"/>
    <step stepNumber="2" action="ENTRY" entity="mesto"/>
    <step stepNumber="3" action="ENTRY" entity="tip"/>
    <step stepNumber="4" action="ENTRY" entity="tempo"/>
    <step stepNumber="5" action="REQUEST_OPERATION" entity="EntityTurnir"/>
    <step stepNumber="6" action="SYSTEM_ACTION" entity="EntityTurnir"/>
    <step stepNumber="7" action="OPERATION_REPORT" entity="EntityTurnir"/>
  </mainScenario>
</useCase>
<useCase 
        usecaseID="UCPocetakTurnira" 
        name="PocetakTurnira" 
        precondition="Nema preduslova" 
        postcondition="Nema postuslova"
        order="4"
        mode="tableMode"
    >
  <actor name="Sudija"/>
  <entity id="EntityTurnir" name="Turnir">
    <attribute id="TurnirID" name="TurnirID" type="NUMBER"  identity="true" validation="structuralContext"/>
    <attribute id="naziv" name="naziv" type= "STRING" validation="domainContext"/>
    <attribute id="mesto" name="mesto" type= "STRING" validation="domainContext" />
    <attribute id="tip" name="tip" type= "STRING" validation="domainContext" />
    <attribute id="tempo" name="tempo" type= "STRING" validation="domainContext" />
  </entity>
  <mainScenario>
    <step stepNumber="1" action="SELECTION" entity="EntityTurnir"/>
    <step stepNumber="2" action="REQUEST_OPERATION" entity="EntityTurnir"/>
    <step stepNumber="3" action="SYSTEM_ACTION" entity="EntityTurnir"/>
    <step stepNumber="4" action="OPERATION_REPORT" entity="EntityTurnir"/>
  </mainScenario>
</useCase>
<useCase 
        usecaseID="UCParovanje" 
        name="Parovanje" 
        precondition="Nema preduslova" 
        postcondition="Nema postuslova"
        order="5"
        mode="tableMode"
    >
  <actor name="Sudija"/>
  <entity id="EntityPartija" name="Partija">
    <attribute id="PartijaID" name="PartijaID" type="NUMBER"  identity="true" validation = "structuralContext"/>
    <attribute id="tabla" name="tabla" type="NUMBER" validation="domainContext"/>
    <attribute id="beli" name="beli" type= "STRING"/>
    <attribute id="crni" name="crni" type= "STRING"/>
    <attribute id="bodovibeli" name="bodovibeli" type= "NUMBER"/>
    <attribute id="bodovicrni" name="bodovicrni" type= "NUMBER"/>
  </entity>
  <mainScenario>
    <step stepNumber="1" action="SELECTION" entity="EntityPartija"/>
    <step stepNumber="2" action="REQUEST_OPERATION" entity="EntityPartija"/>
    <step stepNumber="3" action="SYSTEM_ACTION" entity="EntityPartija"/>
    <step stepNumber="4" action="OPERATION_REPORT" entity="EntityPartija"/>
    <step stepNumber="5" action="REQUEST_OPERATION" entity="EntityPartija"/>
    <step stepNumber="6" action="SYSTEM_ACTION" entity="EntityPartija"/>
    <step stepNumber="7" action="OPERATION_REPORT" entity="EntityPartija"/>
    <step stepNumber="8" action="REQUEST_OPERATION" entity="EntityPartija"/>
    <step stepNumber="9" action="SYSTEM_ACTION" entity="EntityPartija"/>
    <step stepNumber="10" action="OPERATION_REPORT" entity="EntityPartija"/>
  </mainScenario>
</useCase>
<useCase 
        usecaseID="UCPlasman" 
        name="Plasman" 
        precondition="Nema preduslova" 
        postcondition="Nema postuslova"
        order="6"
        mode="tableMode"
    >
  <actor name="Sudija"/>
  <entity id="EntityIgrac" name="Igrac">
    <attribute id="IgracID" name="IgracID" type="NUMBER"  identity="true"/>
    <attribute id="rang" name="rang" type= "NUMBER"/>
    <attribute id="ime" name="ime" type= "STRING"/>
    <attribute id="prezime" name="prezime" type= "STRING"/>
    <attribute id="poeni" name="poeni" type= "NUMBER"/>
  </entity>
  <mainScenario>
    <step stepNumber="1" action="SELECTION" entity="EntityIgrac"/>
    <step stepNumber="2" action="REQUEST_OPERATION" entity="EntityIgrac"/>
    <step stepNumber="3" action="SYSTEM_ACTION" entity="EntityIgrac"/>
    <step stepNumber="4" action="OPERATION_REPORT" entity="EntityIgrac"/>
  </mainScenario>
</useCase>
<useCase 
        usecaseID="UCPregledZavrsenogTurnira" 
        name="PregledZavrsenogTurnira" 
        precondition="Nema preduslova" 
        postcondition="Nema postuslova"
        order="7"
        mode="displayMode"
    >
  <actor name="Sudija"/>
  <entity id="EntityTurnir" name="Turnir">
    <attribute id="TurnirID" name="TurnirID" type="NUMBER"  identity="true"/>
    <attribute id="sudija" name="sudija" type="STRING"/>
    <attribute id="status" name="status" type= "STRING"/>
    <attribute id="prvi" name="prvi" type= "STRING"/>
    <attribute id="drugi" name="drugi" type= "STRING"/>
    <attribute id="treci" name="treci" type= "STRING"/>
  </entity>
  <mainScenario>
    <step stepNumber="1" action="REQUEST_OPERATION" entity="EntityTurnir"/>
    <step stepNumber="2" action="SYSTEM_ACTION" entity="EntityTurnir"/>
    <step stepNumber="3" action="OPERATION_REPORT" entity="EntityTurnir"/>
  </mainScenario>
</useCase>undefined</specification>
